### PR TITLE
Fix dependencies

### PR DESCRIPTION
**Pull request by oliger**
Hi,

`EventListener` has been moved to `fbjs` so I added it as a dependency.

I also moved `React` as a peer dependency.

### CODE REVIEW

**Comment by oliger** [comment]
@glenjamin It seems that test fails... `npm test` starts a node process but does nothing on my machine. Any idea ?

**Comment by oliger** [comment]
re-installing node 0.10 fixed my issue.

**Comment by glenjamin** [comment]
The only reason to use `react`'s event listener in the first place was to avoid pulling in a full dependency.

I think it'd be better to just use a standalone eventemitter module in this case - rather than pulling in the whole fbjs thing.

**Comment by glenjamin** [comment]
Cheers for the PR by the way!

**Comment by oliger** [comment]
@glenjamin `EventListener` as been removed from the latest version of `react`. That is why I'm using fbjs. I'm only importing `EventListener` and not the whole lib. See (https://github.com/hull/react-hotkey/blob/master/index.js#L1).

**Comment by oliger** [comment]
>  think it'd be better to just use a standalone eventemitter module in this case

EventListener is quite small (See https://github.com/facebook/fbjs/blob/master/src/stubs/EventListener.js).

**Comment by glenjamin** [comment]
It does still pull the rest of fbjs into the node_modules folder, and make it a bit harder to decide whether updates are needed.

Could we use something more focused like https://github.com/insin/event-listener instead?

**Comment by oliger** [comment]
@glenjamin done.

**Comment by glenjamin** [comment]
Released as `v0.5.0`

**Pull request merged**
